[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
seeds = false
skip-lint = false

[programs]
[programs.localnet]
barn = "Aoofv5iGzdDeyySpT9QsiFaK7Db7SKyycb7nTEU1oTYE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deployer.json"

[scripts]
test = "ts-mocha -p ./protocol/ts/tsconfig.json -t 1000000 protocol/ts/tests/**/*.test.ts"
barn = "ts-mocha -p ./protocol/ts/tsconfig.json -t 1000000 protocol/ts/tests/barn.test.ts"

[workspace]
members = [ "protocol/programs/*" ]
types = "protocol/ts/src/idl"