[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
seeds = false
skip-lint = false

[programs]
[programs.localnet]
barn = "9r5mFwaKhxmyp6iBQeo3fHXP2J1bGneySwyLmvSq1Ggd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./protocol/ts/tsconfig.node.json -t 1000000 protocol/ts/tests/**/*.test.ts"
barn = "ts-mocha -p ./protocol/ts/tsconfig.node.json -t 1000000 protocol/ts/tests/demo-program.test.ts"

[workspace]
members = [ "protocol/programs/*" ]
types = "protocol/ts/src/idl"